//! https://github.com/llvm/llvm-project/blob/llvmorg-21.1.8/llvm/lib/Object/CMakeLists.txt
//! https://github.com/llvm/llvm-project/blob/llvmorg-21.1.8/llvm/lib/ObjectYAML/CMakeLists.txt
pub const root = "llvm/lib/Object";
pub const sources = [_][]const u8{
    "Archive.cpp",
    "ArchiveWriter.cpp",
    "Binary.cpp",
    "BuildID.cpp",
    "COFFImportFile.cpp",
    "COFFModuleDefinition.cpp",
    "COFFObjectFile.cpp",
    "Decompressor.cpp",
    "DXContainer.cpp",
    "ELF.cpp",
    "ELFObjectFile.cpp",
    "Error.cpp",
    "GOFFObjectFile.cpp",
    "FaultMapParser.cpp",
    "IRObjectFile.cpp",
    "IRSymtab.cpp",
    "MachOObjectFile.cpp",
    "MachOUniversal.cpp",
    "Minidump.cpp",
    "ModuleSymbolTable.cpp",
    "Object.cpp",
    "ObjectFile.cpp",
    "OffloadBinary.cpp",
    "OffloadBundle.cpp",
    "RecordStreamer.cpp",
    "RelocationResolver.cpp",
    "SymbolicFile.cpp",
    "SymbolSize.cpp",
    "TapiFile.cpp",
    "TapiUniversal.cpp",
    "MachOUniversalWriter.cpp",
    "WasmObjectFile.cpp",
    "WindowsMachineFlag.cpp",
    "WindowsResource.cpp",
    "XCOFFObjectFile.cpp",
};

pub const yaml_root = "llvm/lib/ObjectYAML";
pub const yaml_sources = [_][]const u8{
    "ArchiveEmitter.cpp",
    "ArchiveYAML.cpp",
    "CodeViewYAMLDebugSections.cpp",
    "CodeViewYAMLSymbols.cpp",
    "CodeViewYAMLTypeHashing.cpp",
    "CodeViewYAMLTypes.cpp",
    "COFFEmitter.cpp",
    "COFFYAML.cpp",
    "DWARFEmitter.cpp",
    "DWARFYAML.cpp",
    "DXContainerEmitter.cpp",
    "DXContainerYAML.cpp",
    "ELFEmitter.cpp",
    "ELFYAML.cpp",
    "GOFFEmitter.cpp",
    "GOFFYAML.cpp",
    "MachOEmitter.cpp",
    "MachOYAML.cpp",
    "ObjectYAML.cpp",
    "MinidumpEmitter.cpp",
    "MinidumpYAML.cpp",
    "OffloadEmitter.cpp",
    "OffloadYAML.cpp",
    "WasmEmitter.cpp",
    "WasmYAML.cpp",
    "XCOFFEmitter.cpp",
    "XCOFFYAML.cpp",
    "YAML.cpp",
    "yaml2obj.cpp",
};
