var data = {lines:[
{"lineNum":"    1","line":"#include <utility>"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include \"ast/statements/decl.hpp\""},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":"#include \"ast/expressions/function.hpp\""},
{"lineNum":"    6","line":"#include \"ast/expressions/identifier.hpp\""},
{"lineNum":"    7","line":"#include \"ast/expressions/type.hpp\""},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"#include \"visitor/visitor.hpp\""},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"namespace conch::ast {"},
{"lineNum":"   12","line":""},
{"lineNum":"   13","line":"DeclStatement::DeclStatement(const Token&              start_token,"},
{"lineNum":"   14","line":"                             Box<IdentifierExpression> ident,"},
{"lineNum":"   15","line":"                             Box<TypeExpression>       type,"},
{"lineNum":"   16","line":"                             Optional<Box<Expression>> value,"},
{"lineNum":"   17","line":"                             DeclModifiers             modifiers) noexcept"},
{"lineNum":"   18","line":"    : StmtBase{start_token}, ident_{std::move(ident)}, type_{std::move(type)},","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   19","line":"      value_{std::move(value)}, modifiers_{modifiers} {}","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   20","line":""},
{"lineNum":"   21","line":"DeclStatement::~DeclStatement() = default;","class":"lineNoCov","hits":"0","possible_hits":"6",},
{"lineNum":"   22","line":""},
{"lineNum":"   23","line":"auto DeclStatement::accept(Visitor& v) const -> void { v.visit(*this); }","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"   24","line":""},
{"lineNum":"   25","line":"auto DeclStatement::parse(Parser& parser) -> Expected<Box<Statement>, ParserDiagnostic> {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   26","line":"    const auto    start_token = parser.current_token();","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   27","line":"    DeclModifiers modifiers   = token_to_modifier(start_token).value();","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   28","line":""},
{"lineNum":"   29","line":"    Optional<DeclModifiers> current_modifier;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   30","line":"    while ((current_modifier = token_to_modifier(parser.peek_token()))) {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   31","line":"        parser.advance();","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   32","line":"        if (modifiers_has(modifiers, *current_modifier)) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   33","line":"            return make_parser_unexpected(ParserError::DUPLICATE_DECL_MODIFIER, start_token);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   34","line":"        }"},
{"lineNum":"   35","line":"        modifiers |= *current_modifier;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   36","line":"    }"},
{"lineNum":"   37","line":""},
{"lineNum":"   38","line":"    if (!validate_modifiers(modifiers)) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   39","line":"        return make_parser_unexpected(ParserError::ILLEGAL_DECL_MODIFIERS, start_token);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   40","line":"    }"},
{"lineNum":"   41","line":""},
{"lineNum":"   42","line":"    TRY(parser.expect_peek(TokenType::IDENT));","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"   43","line":"    auto decl_name = downcast<IdentifierExpression>(TRY(IdentifierExpression::parse(parser)));","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   44","line":"    auto [decl_type, value_initialized] = TRY(TypeExpression::parse(parser));","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   45","line":"    auto decl_type_expr                 = downcast<TypeExpression>(std::move(decl_type));","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   46","line":""},
{"lineNum":"   47","line":"    Optional<Box<Expression>> decl_value;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   48","line":"    if (value_initialized) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   49","line":"        decl_value = TRY(parser.parse_expression());","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   50","line":"    } else {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   51","line":"        if (modifiers_has(modifiers, DeclModifiers::CONSTANT)) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   52","line":"            return make_parser_unexpected(ParserError::CONST_DECL_MISSING_VALUE, start_token);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   53","line":"        } else if (!decl_type_expr->has_explicit_type()) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   54","line":"            return make_parser_unexpected(ParserError::FORWARD_VAR_DECL_MISSING_TYPE, start_token);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   55","line":"        }"},
{"lineNum":"   56","line":"    }"},
{"lineNum":"   57","line":""},
{"lineNum":"   58","line":"    return make_box<DeclStatement>(start_token,","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   59","line":"                                   std::move(decl_name),"},
{"lineNum":"   60","line":"                                   std::move(decl_type_expr),"},
{"lineNum":"   61","line":"                                   std::move(decl_value),"},
{"lineNum":"   62","line":"                                   modifiers);"},
{"lineNum":"   63","line":"}","class":"lineNoCov","hits":"0","possible_hits":"14",},
{"lineNum":"   64","line":""},
{"lineNum":"   65","line":"auto DeclStatement::is_equal(const Node& other) const noexcept -> bool {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   66","line":"    const auto& casted = as<DeclStatement>(other);","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"   67","line":"    return ident_ == casted.ident_ && type_ == casted.type_ &&","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   68","line":"           optional::unsafe_eq<Expression>(value_, casted.value_) &&","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   69","line":"           modifiers_ == casted.modifiers_;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   70","line":"}"},
{"lineNum":"   71","line":""},
{"lineNum":"   72","line":"} // namespace conch::ast"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "tests", "date" : "2026-02-11 22:34:36", "instrumented" : 34, "covered" : 0,};
var merged_data = [];
