var data = {lines:[
{"lineNum":"    1","line":"#pragma once"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include <memory>"},
{"lineNum":"    4","line":"#include <optional>"},
{"lineNum":"    5","line":"#include <type_traits>"},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"namespace conch {"},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"template <typename T> class OptionalRef {"},
{"lineNum":"   10","line":"  public:"},
{"lineNum":"   11","line":"    OptionalRef() noexcept : ptr_{nullptr} {}"},
{"lineNum":"   12","line":"    OptionalRef(std::nullopt_t) noexcept // cppcheck-suppress noExplicitConstructor"},
{"lineNum":"   13","line":"        : ptr_{nullptr} {}","class":"lineNoCov","hits":"0","possible_hits":"6",},
{"lineNum":"   14","line":"    OptionalRef(T& ref) noexcept : ptr_{&ref} {} // cppcheck-suppress noExplicitConstructor","class":"linePartCov","hits":"3","order":"159","possible_hits":"6",},
{"lineNum":"   15","line":""},
{"lineNum":"   16","line":"    OptionalRef(T&&)                                            = delete;"},
{"lineNum":"   17","line":"    auto operator=(const OptionalRef&) noexcept -> OptionalRef& = default;"},
{"lineNum":"   18","line":""},
{"lineNum":"   19","line":"    [[nodiscard]] bool     has_value() const noexcept { return ptr_ != nullptr; }"},
{"lineNum":"   20","line":"    [[nodiscard]] explicit operator bool() const noexcept { return ptr_ != nullptr; }","class":"linePartCov","hits":"3","order":"162","possible_hits":"6",},
{"lineNum":"   21","line":""},
{"lineNum":"   22","line":"    auto value() const -> T& {"},
{"lineNum":"   23","line":"        if (!ptr_) { throw std::bad_optional_access(); }"},
{"lineNum":"   24","line":"        return *ptr_;"},
{"lineNum":"   25","line":"    }"},
{"lineNum":"   26","line":""},
{"lineNum":"   27","line":"    auto operator->() const noexcept -> T* { return ptr_; }"},
{"lineNum":"   28","line":"    auto operator*() const noexcept -> T& { return *ptr_; }","class":"linePartCov","hits":"3","order":"164","possible_hits":"6",},
{"lineNum":"   29","line":""},
{"lineNum":"   30","line":"  private:"},
{"lineNum":"   31","line":"    T* ptr_;"},
{"lineNum":"   32","line":"};"},
{"lineNum":"   33","line":""},
{"lineNum":"   34","line":"template <typename T>"},
{"lineNum":"   35","line":"using Optional = std::conditional_t<std::is_reference_v<T>,"},
{"lineNum":"   36","line":"                                    OptionalRef<std::remove_reference_t<T>>,"},
{"lineNum":"   37","line":"                                    std::optional<T>>;"},
{"lineNum":"   38","line":""},
{"lineNum":"   39","line":"using std::nullopt;"},
{"lineNum":"   40","line":""},
{"lineNum":"   41","line":"namespace optional {"},
{"lineNum":"   42","line":""},
{"lineNum":"   43","line":"template <typename T>"},
{"lineNum":"   44","line":"auto safe_eq(const Optional<T>& a, const Optional<T>& b, bool (*cmp)(const T&, const T&)) noexcept"},
{"lineNum":"   45","line":"    -> bool {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   46","line":"    if (a.has_value() != b.has_value()) { return false; }","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   47","line":"    if (!a.has_value()) { return true; }","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   48","line":"    return cmp(*a, *b);","class":"lineNoCov","hits":"0","possible_hits":"6",},
{"lineNum":"   49","line":"}","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   50","line":""},
{"lineNum":"   51","line":"template <typename T>"},
{"lineNum":"   52","line":"auto unsafe_eq(const Optional<std::unique_ptr<T>>& a,"},
{"lineNum":"   53","line":"               const Optional<std::unique_ptr<T>>& b,"},
{"lineNum":"   54","line":"               bool (*cmp)(const T&, const T&)) noexcept -> bool {","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   55","line":"    if (a.has_value() != b.has_value()) { return false; }","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   56","line":"    if (!a.has_value()) { return true; }","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   57","line":"    return cmp(**a, **b);","class":"lineNoCov","hits":"0","possible_hits":"12",},
{"lineNum":"   58","line":"}","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   59","line":""},
{"lineNum":"   60","line":"template <typename T>"},
{"lineNum":"   61","line":"auto unsafe_eq(const Optional<std::unique_ptr<T>>& a,"},
{"lineNum":"   62","line":"               const Optional<std::unique_ptr<T>>& b) noexcept -> bool {","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   63","line":"    return unsafe_eq<T>(a, b, [](const T& ae, const T& be) { return ae == be; });","class":"lineNoCov","hits":"0","possible_hits":"32",},
{"lineNum":"   64","line":"}"},
{"lineNum":"   65","line":""},
{"lineNum":"   66","line":"} // namespace optional"},
{"lineNum":"   67","line":""},
{"lineNum":"   68","line":"} // namespace conch"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "tests", "date" : "2026-02-11 22:34:36", "instrumented" : 16, "covered" : 3,};
var merged_data = [];
