var data = {lines:[
{"lineNum":"    1","line":"#include <algorithm>"},
{"lineNum":"    2","line":"#include <array>"},
{"lineNum":"    3","line":"#include <format>"},
{"lineNum":"    4","line":"#include <ranges>"},
{"lineNum":"    5","line":""},
{"lineNum":"    6","line":"#include \"parser/parser.hpp\""},
{"lineNum":"    7","line":"#include \"parser/precedence.hpp\""},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"#include \"lexer/keywords.hpp\""},
{"lineNum":"   10","line":"#include \"lexer/token.hpp\""},
{"lineNum":"   11","line":""},
{"lineNum":"   12","line":"#include \"ast/node.hpp\""},
{"lineNum":"   13","line":"#include \"ast/statements/block.hpp\""},
{"lineNum":"   14","line":"#include \"ast/statements/decl.hpp\""},
{"lineNum":"   15","line":"#include \"ast/statements/discard.hpp\""},
{"lineNum":"   16","line":"#include \"ast/statements/expression.hpp\""},
{"lineNum":"   17","line":"#include \"ast/statements/import.hpp\""},
{"lineNum":"   18","line":"#include \"ast/statements/jump.hpp\""},
{"lineNum":"   19","line":""},
{"lineNum":"   20","line":"#include \"ast/expressions/array.hpp\""},
{"lineNum":"   21","line":"#include \"ast/expressions/assignment.hpp\""},
{"lineNum":"   22","line":"#include \"ast/expressions/binary.hpp\""},
{"lineNum":"   23","line":"#include \"ast/expressions/call.hpp\""},
{"lineNum":"   24","line":"#include \"ast/expressions/do_while.hpp\""},
{"lineNum":"   25","line":"#include \"ast/expressions/for.hpp\""},
{"lineNum":"   26","line":"#include \"ast/expressions/function.hpp\""},
{"lineNum":"   27","line":"#include \"ast/expressions/group.hpp\""},
{"lineNum":"   28","line":"#include \"ast/expressions/identifier.hpp\""},
{"lineNum":"   29","line":"#include \"ast/expressions/if.hpp\""},
{"lineNum":"   30","line":"#include \"ast/expressions/index.hpp\""},
{"lineNum":"   31","line":"#include \"ast/expressions/infinite_loop.hpp\""},
{"lineNum":"   32","line":"#include \"ast/expressions/match.hpp\""},
{"lineNum":"   33","line":"#include \"ast/expressions/prefix.hpp\""},
{"lineNum":"   34","line":"#include \"ast/expressions/primitive.hpp\""},
{"lineNum":"   35","line":"#include \"ast/expressions/range.hpp\""},
{"lineNum":"   36","line":"#include \"ast/expressions/scope_resolve.hpp\""},
{"lineNum":"   37","line":"#include \"ast/expressions/struct.hpp\""},
{"lineNum":"   38","line":"#include \"ast/expressions/while.hpp\""},
{"lineNum":"   39","line":""},
{"lineNum":"   40","line":"namespace conch {"},
{"lineNum":"   41","line":""},
{"lineNum":"   42","line":"auto Parser::reset(std::string_view input) noexcept -> void { *this = Parser{input}; }","class":"lineCov","hits":"3","order":"138","possible_hits":"3",},
{"lineNum":"   43","line":""},
{"lineNum":"   44","line":"auto Parser::advance(uint8_t times) noexcept -> const Token& {","class":"lineCov","hits":"2","order":"24","possible_hits":"2",},
{"lineNum":"   45","line":"    for (uint8_t i = 0; i < times; ++i) {","class":"lineCov","hits":"2","order":"25","possible_hits":"2",},
{"lineNum":"   46","line":"        if (current_token_.type == TokenType::END &&","class":"linePartCov","hits":"1","order":"26","possible_hits":"2",},
{"lineNum":"   47","line":"            (input_.empty() && current_token_.location.at_start())) {","class":"lineCov","hits":"1","order":"27","possible_hits":"1",},
{"lineNum":"   48","line":"            break;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   49","line":"        }"},
{"lineNum":"   50","line":""},
{"lineNum":"   51","line":"        current_token_ = peek_token_;","class":"lineCov","hits":"1","order":"28","possible_hits":"1",},
{"lineNum":"   52","line":"        peek_token_    = lexer_.advance();","class":"lineCov","hits":"1","order":"29","possible_hits":"1",},
{"lineNum":"   53","line":"    }"},
{"lineNum":"   54","line":"    return current_token_;","class":"lineCov","hits":"1","order":"135","possible_hits":"1",},
{"lineNum":"   55","line":"}"},
{"lineNum":"   56","line":""},
{"lineNum":"   57","line":"auto Parser::consume() -> std::pair<ast::AST, std::span<const ParserDiagnostic>> {","class":"lineCov","hits":"2","order":"136","possible_hits":"2",},
{"lineNum":"   58","line":"    reset(input_);","class":"lineCov","hits":"1","order":"137","possible_hits":"1",},
{"lineNum":"   59","line":"    ast::AST ast;","class":"lineCov","hits":"1","order":"140","possible_hits":"1",},
{"lineNum":"   60","line":""},
{"lineNum":"   61","line":"    while (!current_token_is(TokenType::END)) {","class":"lineCov","hits":"2","order":"141","possible_hits":"2",},
{"lineNum":"   62","line":"        if (!current_token_is(TokenType::COMMENT)) {","class":"lineCov","hits":"1","order":"143","possible_hits":"1",},
{"lineNum":"   63","line":"            auto stmt = parse_statement();","class":"lineCov","hits":"1","order":"144","possible_hits":"1",},
{"lineNum":"   64","line":"            if (peek_token_is(TokenType::SEMICOLON)) { advance(); }","class":"lineCov","hits":"1","order":"218","possible_hits":"1",},
{"lineNum":"   65","line":"            if (stmt) {","class":"lineCov","hits":"1","order":"219","possible_hits":"1",},
{"lineNum":"   66","line":"                ast.emplace_back(std::move(*stmt));","class":"lineCov","hits":"1","order":"220","possible_hits":"1",},
{"lineNum":"   67","line":"            } else {","class":"lineCov","hits":"1","order":"221","possible_hits":"1",},
{"lineNum":"   68","line":"                diagnostics_.emplace_back(std::move(stmt.error()));","class":"lineCov","hits":"1","order":"277","possible_hits":"1",},
{"lineNum":"   69","line":"            }"},
{"lineNum":"   70","line":"        }","class":"linePartCov","hits":"1","order":"222","possible_hits":"2",},
{"lineNum":"   71","line":"        advance();","class":"lineCov","hits":"1","order":"223","possible_hits":"1",},
{"lineNum":"   72","line":"    }"},
{"lineNum":"   73","line":""},
{"lineNum":"   74","line":"    return {std::move(ast), diagnostics_};","class":"lineCov","hits":"1","order":"224","possible_hits":"1",},
{"lineNum":"   75","line":"}","class":"linePartCov","hits":"1","order":"225","possible_hits":"3",},
{"lineNum":"   76","line":""},
{"lineNum":"   77","line":"auto Parser::expect_current(TokenType expected) -> Expected<std::monostate, ParserDiagnostic> {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   78","line":"    if (current_token_is(expected)) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   79","line":"        advance();","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   80","line":"        return {};","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   81","line":"    }"},
{"lineNum":"   82","line":"    return Unexpected{current_error(expected)};","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   83","line":"}","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   84","line":""},
{"lineNum":"   85","line":"auto Parser::expect_peek(TokenType expected) -> Expected<std::monostate, ParserDiagnostic> {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   86","line":"    if (peek_token_is(expected)) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   87","line":"        advance();","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   88","line":"        return {};","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   89","line":"    }"},
{"lineNum":"   90","line":"    return Unexpected{peek_error(expected)};","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   91","line":"}","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   92","line":""},
{"lineNum":"   93","line":"auto Parser::current_precedence() const noexcept -> Precedence {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   94","line":"    return get_binding(current_token_.type)","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   95","line":"        .transform([](const auto& binding) { return binding.second; })","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   96","line":"        .value_or(Precedence::LOWEST);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   97","line":"}"},
{"lineNum":"   98","line":""},
{"lineNum":"   99","line":"auto Parser::peek_precedence() const noexcept -> Precedence {","class":"lineCov","hits":"2","order":"202","possible_hits":"2",},
{"lineNum":"  100","line":"    return get_binding(peek_token_.type)","class":"lineCov","hits":"2","order":"203","possible_hits":"2",},
{"lineNum":"  101","line":"        .transform([](const auto& binding) { return binding.second; })","class":"linePartCov","hits":"1","order":"208","possible_hits":"4",},
{"lineNum":"  102","line":"        .value_or(Precedence::LOWEST);","class":"lineCov","hits":"1","order":"209","possible_hits":"1",},
{"lineNum":"  103","line":"}"},
{"lineNum":"  104","line":""},
{"lineNum":"  105","line":"auto Parser::parse_statement() -> Expected<Box<ast::Statement>, ParserDiagnostic> {","class":"lineCov","hits":"2","order":"145","possible_hits":"2",},
{"lineNum":"  106","line":"    switch (current_token_.type) {","class":"lineCov","hits":"1","order":"146","possible_hits":"1",},
{"lineNum":"  107","line":"    case TokenType::VAR:"},
{"lineNum":"  108","line":"    case TokenType::CONST:"},
{"lineNum":"  109","line":"    case TokenType::PRIVATE:"},
{"lineNum":"  110","line":"    case TokenType::EXTERN:"},
{"lineNum":"  111","line":"    case TokenType::EXPORT:     return ast::DeclStatement::parse(*this);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  112","line":"    case TokenType::BREAK:"},
{"lineNum":"  113","line":"    case TokenType::RETURN:"},
{"lineNum":"  114","line":"    case TokenType::CONTINUE:   return ast::JumpStatement::parse(*this);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  115","line":"    case TokenType::IMPORT:     return ast::ImportStatement::parse(*this);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  116","line":"    case TokenType::LBRACE:     return ast::BlockStatement::parse(*this);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  117","line":"    case TokenType::UNDERSCORE: return ast::DiscardStatement::parse(*this);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  118","line":"    default:                    return ast::ExpressionStatement::parse(*this);","class":"lineCov","hits":"1","order":"147","possible_hits":"1",},
{"lineNum":"  119","line":"    }"},
{"lineNum":"  120","line":""},
{"lineNum":"  121","line":"    std::unreachable();"},
{"lineNum":"  122","line":"}","class":"linePartCov","hits":"1","order":"217","possible_hits":"2",},
{"lineNum":"  123","line":""},
{"lineNum":"  124","line":"auto Parser::parse_expression(Precedence precedence)"},
{"lineNum":"  125","line":"    -> Expected<Box<ast::Expression>, ParserDiagnostic> {","class":"lineCov","hits":"2","order":"152","possible_hits":"2",},
{"lineNum":"  126","line":"    if (current_token_is(TokenType::END)) {","class":"lineCov","hits":"1","order":"153","possible_hits":"1",},
{"lineNum":"  127","line":"        return make_parser_unexpected(ParserError::END_OF_TOKEN_STREAM, current_token_);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  128","line":"    }"},
{"lineNum":"  129","line":""},
{"lineNum":"  130","line":"    const auto& prefix = poll_prefix(current_token_.type);","class":"lineCov","hits":"1","order":"154","possible_hits":"1",},
{"lineNum":"  131","line":"    if (!prefix) {","class":"lineCov","hits":"1","order":"161","possible_hits":"1",},
{"lineNum":"  132","line":"        return make_parser_unexpected(","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  133","line":"            std::format(\"No prefix parse function for {} found\", enum_name(current_token_.type)),","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  134","line":"            ParserError::MISSING_PREFIX_PARSER,","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  135","line":"            current_token_);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  136","line":"    }"},
{"lineNum":"  137","line":"    auto lhs_expression = TRY((*prefix)(*this));","class":"linePartCov","hits":"1","order":"163","possible_hits":"2",},
{"lineNum":"  138","line":""},
{"lineNum":"  139","line":"    while (!peek_token_is(TokenType::SEMICOLON) && precedence < peek_precedence()) {","class":"linePartCov","hits":"1","order":"200","possible_hits":"2",},
{"lineNum":"  140","line":"        const auto& infix = poll_infix(peek_token_.type);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  141","line":"        if (!infix) { break; }","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  142","line":""},
{"lineNum":"  143","line":"        if (advance().type == TokenType::END) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  144","line":"            return make_parser_unexpected(ParserError::INFIX_MISSING_RHS, current_token_);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  145","line":"        }"},
{"lineNum":"  146","line":""},
{"lineNum":"  147","line":"        lhs_expression = TRY((*infix)(*this, std::move(lhs_expression)));","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  148","line":"    }"},
{"lineNum":"  149","line":""},
{"lineNum":"  150","line":"    return lhs_expression;","class":"lineCov","hits":"1","order":"210","possible_hits":"1",},
{"lineNum":"  151","line":"}","class":"linePartCov","hits":"2","order":"211","possible_hits":"8",},
{"lineNum":"  152","line":""},
{"lineNum":"  153","line":"using PrefixPair          = std::pair<TokenType, Parser::PrefixFn>;"},
{"lineNum":"  154","line":"constexpr auto PREFIX_FNS = []() {"},
{"lineNum":"  155","line":"    constexpr auto initial_prefixes = std::to_array<PrefixPair>({"},
{"lineNum":"  156","line":"        {TokenType::IDENT, ast::IdentifierExpression::parse},"},
{"lineNum":"  157","line":"        {TokenType::INT_2, ast::SignedIntegerExpression::parse},"},
{"lineNum":"  158","line":"        {TokenType::INT_8, ast::SignedIntegerExpression::parse},"},
{"lineNum":"  159","line":"        {TokenType::INT_10, ast::SignedIntegerExpression::parse},"},
{"lineNum":"  160","line":"        {TokenType::INT_16, ast::SignedIntegerExpression::parse},"},
{"lineNum":"  161","line":"        {TokenType::LINT_2, ast::SignedLongIntegerExpression::parse},"},
{"lineNum":"  162","line":"        {TokenType::LINT_8, ast::SignedLongIntegerExpression::parse},"},
{"lineNum":"  163","line":"        {TokenType::LINT_10, ast::SignedLongIntegerExpression::parse},"},
{"lineNum":"  164","line":"        {TokenType::LINT_16, ast::SignedLongIntegerExpression::parse},"},
{"lineNum":"  165","line":"        {TokenType::ZINT_2, ast::ISizeIntegerExpression::parse},"},
{"lineNum":"  166","line":"        {TokenType::ZINT_8, ast::ISizeIntegerExpression::parse},"},
{"lineNum":"  167","line":"        {TokenType::ZINT_10, ast::ISizeIntegerExpression::parse},"},
{"lineNum":"  168","line":"        {TokenType::ZINT_16, ast::ISizeIntegerExpression::parse},"},
{"lineNum":"  169","line":"        {TokenType::UINT_2, ast::UnsignedIntegerExpression::parse},"},
{"lineNum":"  170","line":"        {TokenType::UINT_8, ast::UnsignedIntegerExpression::parse},"},
{"lineNum":"  171","line":"        {TokenType::UINT_10, ast::UnsignedIntegerExpression::parse},"},
{"lineNum":"  172","line":"        {TokenType::UINT_16, ast::UnsignedIntegerExpression::parse},"},
{"lineNum":"  173","line":"        {TokenType::ULINT_2, ast::UnsignedLongIntegerExpression::parse},"},
{"lineNum":"  174","line":"        {TokenType::ULINT_8, ast::UnsignedLongIntegerExpression::parse},"},
{"lineNum":"  175","line":"        {TokenType::ULINT_10, ast::UnsignedLongIntegerExpression::parse},"},
{"lineNum":"  176","line":"        {TokenType::ULINT_16, ast::UnsignedLongIntegerExpression::parse},"},
{"lineNum":"  177","line":"        {TokenType::UZINT_2, ast::USizeIntegerExpression::parse},"},
{"lineNum":"  178","line":"        {TokenType::UZINT_8, ast::USizeIntegerExpression::parse},"},
{"lineNum":"  179","line":"        {TokenType::UZINT_10, ast::USizeIntegerExpression::parse},"},
{"lineNum":"  180","line":"        {TokenType::UZINT_16, ast::USizeIntegerExpression::parse},"},
{"lineNum":"  181","line":"        {TokenType::BYTE, ast::ByteExpression::parse},"},
{"lineNum":"  182","line":"        {TokenType::FLOAT, ast::FloatExpression::parse},"},
{"lineNum":"  183","line":"        {TokenType::BANG, ast::PrefixExpression::parse},"},
{"lineNum":"  184","line":"        {TokenType::NOT, ast::PrefixExpression::parse},"},
{"lineNum":"  185","line":"        {TokenType::MINUS, ast::PrefixExpression::parse},"},
{"lineNum":"  186","line":"        {TokenType::TRUE, ast::BoolExpression::parse},"},
{"lineNum":"  187","line":"        {TokenType::FALSE, ast::BoolExpression::parse},"},
{"lineNum":"  188","line":"        {TokenType::STRING, ast::StringExpression::parse},"},
{"lineNum":"  189","line":"        {TokenType::MULTILINE_STRING, ast::StringExpression::parse},"},
{"lineNum":"  190","line":"        {TokenType::LPAREN, ast::GroupedExpression::parse},"},
{"lineNum":"  191","line":"        {TokenType::IF, ast::IfExpression::parse},"},
{"lineNum":"  192","line":"        {TokenType::FUNCTION, ast::FunctionExpression::parse},"},
{"lineNum":"  193","line":"        {TokenType::MUT, ast::FunctionExpression::parse},"},
{"lineNum":"  194","line":"        {TokenType::PACKED, ast::StructExpression::parse},"},
{"lineNum":"  195","line":"        {TokenType::STRUCT, ast::StructExpression::parse},"},
{"lineNum":"  196","line":"        {TokenType::ENUM, ast::FunctionExpression::parse},"},
{"lineNum":"  197","line":"        {TokenType::NIL, ast::NilExpression::parse},"},
{"lineNum":"  198","line":"        {TokenType::MATCH, ast::MatchExpression::parse},"},
{"lineNum":"  199","line":"        {TokenType::LBRACKET, ast::ArrayExpression::parse},"},
{"lineNum":"  200","line":"        {TokenType::FOR, ast::ForLoopExpression::parse},"},
{"lineNum":"  201","line":"        {TokenType::WHILE, ast::WhileLoopExpression::parse},"},
{"lineNum":"  202","line":"        {TokenType::DO, ast::DoWhileLoopExpression::parse},"},
{"lineNum":"  203","line":"        {TokenType::LOOP, ast::InfiniteLoopExpression::parse},"},
{"lineNum":"  204","line":"    });"},
{"lineNum":"  205","line":""},
{"lineNum":"  206","line":"    constexpr auto primitive_prefixes ="},
{"lineNum":"  207","line":"        ALL_PRIMITIVES | std::views::transform([](TokenType tt) -> PrefixPair {"},
{"lineNum":"  208","line":"            return {tt, ast::IdentifierExpression::parse};"},
{"lineNum":"  209","line":"        });"},
{"lineNum":"  210","line":""},
{"lineNum":"  211","line":"    constexpr auto materialized_primitives ="},
{"lineNum":"  212","line":"        materialize_sized_view<ALL_PRIMITIVES.size()>(primitive_prefixes);"},
{"lineNum":"  213","line":""},
{"lineNum":"  214","line":"    constexpr auto builtins_prefixes ="},
{"lineNum":"  215","line":"        ALL_BUILTINS | std::views::transform([](const auto& builtin) -> PrefixPair {"},
{"lineNum":"  216","line":"            return {builtin.second, ast::IdentifierExpression::parse};"},
{"lineNum":"  217","line":"        });"},
{"lineNum":"  218","line":""},
{"lineNum":"  219","line":"    constexpr auto materialized_builtins ="},
{"lineNum":"  220","line":"        materialize_sized_view<ALL_BUILTINS.size()>(builtins_prefixes);"},
{"lineNum":"  221","line":""},
{"lineNum":"  222","line":"    auto prefix_fns ="},
{"lineNum":"  223","line":"        concat_arrays(initial_prefixes, materialized_primitives, materialized_builtins);"},
{"lineNum":"  224","line":"    std::ranges::sort(prefix_fns, {}, &PrefixPair::first);"},
{"lineNum":"  225","line":"    return prefix_fns;"},
{"lineNum":"  226","line":"}();"},
{"lineNum":"  227","line":""},
{"lineNum":"  228","line":"constexpr auto Parser::poll_prefix(TokenType tt) noexcept -> Optional<const PrefixFn&> {","class":"lineCov","hits":"1","order":"155","possible_hits":"1",},
{"lineNum":"  229","line":"    const auto it = std::ranges::lower_bound(PREFIX_FNS, tt, {}, &PrefixPair::first);","class":"linePartCov","hits":"1","order":"156","possible_hits":"2",},
{"lineNum":"  230","line":"    if (it == PREFIX_FNS.end() || it->first != tt) { return nullopt; }","class":"lineCov","hits":"1","order":"157","possible_hits":"1",},
{"lineNum":"  231","line":"    return Optional<const PrefixFn&>{it->second};","class":"lineCov","hits":"1","order":"158","possible_hits":"1",},
{"lineNum":"  232","line":"}","class":"lineCov","hits":"1","order":"160","possible_hits":"1",},
{"lineNum":"  233","line":""},
{"lineNum":"  234","line":"using InfixPair          = std::pair<TokenType, Parser::InfixFn>;"},
{"lineNum":"  235","line":"constexpr auto INFIX_FNS = []() {"},
{"lineNum":"  236","line":"    auto infix_fns = std::to_array<InfixPair>({"},
{"lineNum":"  237","line":"        {TokenType::PLUS, ast::BinaryExpression::parse},"},
{"lineNum":"  238","line":"        {TokenType::MINUS, ast::BinaryExpression::parse},"},
{"lineNum":"  239","line":"        {TokenType::STAR, ast::BinaryExpression::parse},"},
{"lineNum":"  240","line":"        {TokenType::SLASH, ast::BinaryExpression::parse},"},
{"lineNum":"  241","line":"        {TokenType::PERCENT, ast::BinaryExpression::parse},"},
{"lineNum":"  242","line":"        {TokenType::STAR_STAR, ast::BinaryExpression::parse},"},
{"lineNum":"  243","line":"        {TokenType::LT, ast::BinaryExpression::parse},"},
{"lineNum":"  244","line":"        {TokenType::LTEQ, ast::BinaryExpression::parse},"},
{"lineNum":"  245","line":"        {TokenType::GT, ast::BinaryExpression::parse},"},
{"lineNum":"  246","line":"        {TokenType::GTEQ, ast::BinaryExpression::parse},"},
{"lineNum":"  247","line":"        {TokenType::EQ, ast::BinaryExpression::parse},"},
{"lineNum":"  248","line":"        {TokenType::NEQ, ast::BinaryExpression::parse},"},
{"lineNum":"  249","line":"        {TokenType::BOOLEAN_AND, ast::BinaryExpression::parse},"},
{"lineNum":"  250","line":"        {TokenType::BOOLEAN_OR, ast::BinaryExpression::parse},"},
{"lineNum":"  251","line":"        {TokenType::AND, ast::BinaryExpression::parse},"},
{"lineNum":"  252","line":"        {TokenType::OR, ast::BinaryExpression::parse},"},
{"lineNum":"  253","line":"        {TokenType::XOR, ast::BinaryExpression::parse},"},
{"lineNum":"  254","line":"        {TokenType::SHR, ast::BinaryExpression::parse},"},
{"lineNum":"  255","line":"        {TokenType::SHL, ast::BinaryExpression::parse},"},
{"lineNum":"  256","line":"        {TokenType::IS, ast::BinaryExpression::parse},"},
{"lineNum":"  257","line":"        {TokenType::IN, ast::BinaryExpression::parse},"},
{"lineNum":"  258","line":"        {TokenType::DOT_DOT, ast::RangeExpression::parse},"},
{"lineNum":"  259","line":"        {TokenType::DOT_DOT_EQ, ast::RangeExpression::parse},"},
{"lineNum":"  260","line":"        {TokenType::ORELSE, ast::BinaryExpression::parse},"},
{"lineNum":"  261","line":"        {TokenType::LPAREN, ast::CallExpression::parse},"},
{"lineNum":"  262","line":"        {TokenType::LBRACKET, ast::IndexExpression::parse},"},
{"lineNum":"  263","line":"        {TokenType::ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  264","line":"        {TokenType::PLUS_ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  265","line":"        {TokenType::MINUS_ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  266","line":"        {TokenType::STAR_ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  267","line":"        {TokenType::SLASH_ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  268","line":"        {TokenType::PERCENT_ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  269","line":"        {TokenType::AND_ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  270","line":"        {TokenType::OR_ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  271","line":"        {TokenType::SHL_ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  272","line":"        {TokenType::SHR_ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  273","line":"        {TokenType::NOT_ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  274","line":"        {TokenType::XOR_ASSIGN, ast::AssignmentExpression::parse},"},
{"lineNum":"  275","line":"        {TokenType::COLON_COLON, ast::ScopeResolutionExpression::parse},"},
{"lineNum":"  276","line":"    });"},
{"lineNum":"  277","line":""},
{"lineNum":"  278","line":"    std::ranges::sort(infix_fns, {}, &InfixPair::first);"},
{"lineNum":"  279","line":"    return infix_fns;"},
{"lineNum":"  280","line":"}();"},
{"lineNum":"  281","line":""},
{"lineNum":"  282","line":"constexpr auto Parser::poll_infix(TokenType tt) noexcept -> Optional<const InfixFn&> {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  283","line":"    const auto it = std::ranges::lower_bound(INFIX_FNS, tt, {}, &InfixPair::first);","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  284","line":"    if (it == INFIX_FNS.end() || it->first != tt) { return nullopt; }","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  285","line":"    return Optional<const InfixFn&>{it->second};","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  286","line":"}","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  287","line":""},
{"lineNum":"  288","line":"auto Parser::tt_mismatch_error(TokenType expected, const Token& actual) -> ParserDiagnostic {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  289","line":"    return ParserDiagnostic{","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  290","line":"        std::format(\"Expected token {}, found {}\", enum_name(expected), enum_name(actual.type)),","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  291","line":"        ParserError::UNEXPECTED_TOKEN,"},
{"lineNum":"  292","line":"        actual};","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  293","line":"}","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  294","line":""},
{"lineNum":"  295","line":"} // namespace conch"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "tests", "date" : "2026-02-11 22:34:36", "instrumented" : 86, "covered" : 44,};
var merged_data = [];
