var data = {lines:[
{"lineNum":"    1","line":"#pragma once"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include <utility>"},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":"#include \"ast/node.hpp\""},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"#include \"parser/parser.hpp\""},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"namespace conch::ast {"},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"class DiscardStatement : public StmtBase<DiscardStatement> {","class":"lineCov","hits":"1","order":"1897",},
{"lineNum":"   12","line":"  public:"},
{"lineNum":"   13","line":"    static constexpr auto KIND = NodeKind::DISCARD_STATEMENT;"},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"  public:"},
{"lineNum":"   16","line":"    explicit DiscardStatement(const Token& start_token, Box<Expression> discarded) noexcept"},
{"lineNum":"   17","line":"        : StmtBase{start_token}, discarded_{std::move(discarded)} {}","class":"lineCov","hits":"1","order":"1895",},
{"lineNum":"   18","line":""},
{"lineNum":"   19","line":"    MAKE_AST_COPY_MOVE(DiscardStatement)"},
{"lineNum":"   20","line":""},
{"lineNum":"   21","line":"    auto                      accept(Visitor& v) const -> void override;"},
{"lineNum":"   22","line":"    [[nodiscard]] static auto parse(Parser& parser) -> Expected<Box<Statement>, ParserDiagnostic>;"},
{"lineNum":"   23","line":""},
{"lineNum":"   24","line":"    MAKE_AST_GETTER(discarded, const Expression&, *)","class":"lineCov","hits":"1","order":"1892",},
{"lineNum":"   25","line":""},
{"lineNum":"   26","line":"  protected:"},
{"lineNum":"   27","line":"    auto is_equal(const Node& other) const noexcept -> bool override {","class":"lineCov","hits":"1","order":"1896",},
{"lineNum":"   28","line":"        const auto& casted = as<DiscardStatement>(other);","class":"lineCov","hits":"1","order":"1894",},
{"lineNum":"   29","line":"        return *discarded_ == *casted.discarded_;","class":"lineCov","hits":"1","order":"1893",},
{"lineNum":"   30","line":"    }"},
{"lineNum":"   31","line":""},
{"lineNum":"   32","line":"  private:"},
{"lineNum":"   33","line":"    Box<Expression> discarded_;"},
{"lineNum":"   34","line":"};"},
{"lineNum":"   35","line":""},
{"lineNum":"   36","line":"} // namespace conch::ast"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-03-13 16:31:19", "instrumented" : 6, "covered" : 6,};
var merged_data = [];
