var data = {lines:[
{"lineNum":"    1","line":"#pragma once"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include \"ast/node.hpp\""},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":"#include \"parser/parser.hpp\""},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"namespace conch::ast {"},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"class BlockStatement;"},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"class InfiniteLoopExpression : public ExprBase<InfiniteLoopExpression> {"},
{"lineNum":"   12","line":"  public:"},
{"lineNum":"   13","line":"    static constexpr auto KIND = NodeKind::INFINITE_LOOP_EXPRESSION;"},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"  public:"},
{"lineNum":"   16","line":"    explicit InfiniteLoopExpression(const Token& start_token, Box<BlockStatement> block) noexcept;"},
{"lineNum":"   17","line":"    ~InfiniteLoopExpression() override;"},
{"lineNum":"   18","line":""},
{"lineNum":"   19","line":"    MAKE_AST_COPY_MOVE(InfiniteLoopExpression)","class":"lineCov","hits":"1","order":"1437",},
{"lineNum":"   20","line":""},
{"lineNum":"   21","line":"    auto                      accept(Visitor& v) const -> void override;"},
{"lineNum":"   22","line":"    [[nodiscard]] static auto parse(Parser& parser) -> Expected<Box<Expression>, ParserDiagnostic>;"},
{"lineNum":"   23","line":""},
{"lineNum":"   24","line":"    MAKE_AST_GETTER(block, const BlockStatement&, *)","class":"lineCov","hits":"1","order":"1438",},
{"lineNum":"   25","line":""},
{"lineNum":"   26","line":"  protected:"},
{"lineNum":"   27","line":"    auto is_equal(const Node& other) const noexcept -> bool override;"},
{"lineNum":"   28","line":""},
{"lineNum":"   29","line":"  private:"},
{"lineNum":"   30","line":"    Box<BlockStatement> block_;"},
{"lineNum":"   31","line":"};"},
{"lineNum":"   32","line":""},
{"lineNum":"   33","line":"} // namespace conch::ast"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-03-13 16:31:19", "instrumented" : 2, "covered" : 2,};
var merged_data = [];
