var data = {lines:[
{"lineNum":"    1","line":"#include <utility>"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include \"ast/statements/using.hpp\""},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":"#include \"ast/expressions/function.hpp\""},
{"lineNum":"    6","line":"#include \"ast/expressions/identifier.hpp\""},
{"lineNum":"    7","line":"#include \"ast/visitor.hpp\""},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"namespace conch::ast {"},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"UsingStatement::UsingStatement(const Token&              start_token,"},
{"lineNum":"   12","line":"                               Box<IdentifierExpression> alias,"},
{"lineNum":"   13","line":"                               ExplicitType&&            type) noexcept"},
{"lineNum":"   14","line":"    : StmtBase{start_token}, alias_{std::move(alias)}, type_{std::move(type)} {}","class":"lineCov","hits":"1","order":"1053",},
{"lineNum":"   15","line":"UsingStatement::~UsingStatement() = default;","class":"lineCov","hits":"1","order":"1050",},
{"lineNum":"   16","line":""},
{"lineNum":"   17","line":"auto UsingStatement::accept(Visitor& v) const -> void { v.visit(*this); }","class":"lineCov","hits":"1","order":"1048",},
{"lineNum":"   18","line":""},
{"lineNum":"   19","line":"auto UsingStatement::parse(Parser& parser) -> Expected<Box<Statement>, ParserDiagnostic> {","class":"lineCov","hits":"1","order":"1051",},
{"lineNum":"   20","line":"    const auto start_token = parser.current_token();","class":"lineCov","hits":"1","order":"1049",},
{"lineNum":"   21","line":"    TRY(parser.expect_peek(TokenType::IDENT));","class":"lineCov","hits":"1","order":"1047",},
{"lineNum":"   22","line":"    auto alias = downcast<IdentifierExpression>(TRY(IdentifierExpression::parse(parser)));","class":"lineCov","hits":"1","order":"1046",},
{"lineNum":"   23","line":""},
{"lineNum":"   24","line":"    TRY(parser.expect_peek(TokenType::ASSIGN));","class":"lineCov","hits":"1","order":"1044",},
{"lineNum":"   25","line":"    auto type = TRY(ExplicitType::parse(parser));","class":"lineCov","hits":"1","order":"1052",},
{"lineNum":"   26","line":""},
{"lineNum":"   27","line":"    TRY(parser.expect_peek(TokenType::SEMICOLON));","class":"lineCov","hits":"1","order":"1043",},
{"lineNum":"   28","line":"    return make_box<UsingStatement>(start_token, std::move(alias), std::move(type));","class":"lineCov","hits":"1","order":"1042",},
{"lineNum":"   29","line":"}","class":"lineCov","hits":"1","order":"1045",},
{"lineNum":"   30","line":""},
{"lineNum":"   31","line":"auto UsingStatement::is_equal(const Node& other) const noexcept -> bool {","class":"lineCov","hits":"1","order":"1041",},
{"lineNum":"   32","line":"    const auto& casted = as<UsingStatement>(other);","class":"lineCov","hits":"1","order":"1040",},
{"lineNum":"   33","line":"    return *alias_ == *casted.alias_ && type_ == casted.type_;","class":"lineCov","hits":"1","order":"1039",},
{"lineNum":"   34","line":"}"},
{"lineNum":"   35","line":""},
{"lineNum":"   36","line":"} // namespace conch::ast"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-03-13 16:31:19", "instrumented" : 15, "covered" : 15,};
var merged_data = [];
