var data = {lines:[
{"lineNum":"    1","line":"#pragma once"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"namespace conch::ast {"},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":"#define FOREACH_AST_NODE(X)          \\"},
{"lineNum":"    6","line":"    X(ArrayExpression)               \\"},
{"lineNum":"    7","line":"    X(CallExpression)                \\"},
{"lineNum":"    8","line":"    X(DoWhileLoopExpression)         \\"},
{"lineNum":"    9","line":"    X(EnumExpression)                \\"},
{"lineNum":"   10","line":"    X(ForLoopExpression)             \\"},
{"lineNum":"   11","line":"    X(FunctionExpression)            \\"},
{"lineNum":"   12","line":"    X(IdentifierExpression)          \\"},
{"lineNum":"   13","line":"    X(IfExpression)                  \\"},
{"lineNum":"   14","line":"    X(IndexExpression)               \\"},
{"lineNum":"   15","line":"    X(InfiniteLoopExpression)        \\"},
{"lineNum":"   16","line":"    X(AssignmentExpression)          \\"},
{"lineNum":"   17","line":"    X(BinaryExpression)              \\"},
{"lineNum":"   18","line":"    X(DotExpression)                 \\"},
{"lineNum":"   19","line":"    X(RangeExpression)               \\"},
{"lineNum":"   20","line":"    X(ImplicitDereferenceExpression) \\"},
{"lineNum":"   21","line":"    X(MatchExpression)               \\"},
{"lineNum":"   22","line":"    X(ReferenceExpression)           \\"},
{"lineNum":"   23","line":"    X(DereferenceExpression)         \\"},
{"lineNum":"   24","line":"    X(ImplicitAccessExpression)      \\"},
{"lineNum":"   25","line":"    X(UnaryExpression)               \\"},
{"lineNum":"   26","line":"    X(StringExpression)              \\"},
{"lineNum":"   27","line":"    X(SignedIntegerExpression)       \\"},
{"lineNum":"   28","line":"    X(SignedLongIntegerExpression)   \\"},
{"lineNum":"   29","line":"    X(ISizeIntegerExpression)        \\"},
{"lineNum":"   30","line":"    X(UnsignedIntegerExpression)     \\"},
{"lineNum":"   31","line":"    X(UnsignedLongIntegerExpression) \\"},
{"lineNum":"   32","line":"    X(USizeIntegerExpression)        \\"},
{"lineNum":"   33","line":"    X(ByteExpression)                \\"},
{"lineNum":"   34","line":"    X(FloatExpression)               \\"},
{"lineNum":"   35","line":"    X(DoubleExpression)              \\"},
{"lineNum":"   36","line":"    X(BoolExpression)                \\"},
{"lineNum":"   37","line":"    X(ScopeResolutionExpression)     \\"},
{"lineNum":"   38","line":"    X(StructExpression)              \\"},
{"lineNum":"   39","line":"    X(TypeExpression)                \\"},
{"lineNum":"   40","line":"    X(UnionExpression)               \\"},
{"lineNum":"   41","line":"    X(WhileLoopExpression)           \\"},
{"lineNum":"   42","line":"    X(BlockStatement)                \\"},
{"lineNum":"   43","line":"    X(DeclStatement)                 \\"},
{"lineNum":"   44","line":"    X(DeferStatement)                \\"},
{"lineNum":"   45","line":"    X(DiscardStatement)              \\"},
{"lineNum":"   46","line":"    X(ExpressionStatement)           \\"},
{"lineNum":"   47","line":"    X(ImportStatement)               \\"},
{"lineNum":"   48","line":"    X(JumpStatement)                 \\"},
{"lineNum":"   49","line":"    X(UsingStatement)"},
{"lineNum":"   50","line":""},
{"lineNum":"   51","line":"// The following use \'()\' since it messes with Zed\'s syntax highlighting otherwise :("},
{"lineNum":"   52","line":""},
{"lineNum":"   53","line":"#define FORWARD_DECLARE_NODE(NodeType) class NodeType;"},
{"lineNum":"   54","line":"#define FORWARD_DECLARE_AST_NODES() FOREACH_AST_NODE(FORWARD_DECLARE_NODE)"},
{"lineNum":"   55","line":""},
{"lineNum":"   56","line":"#define GENERATE_ABSTRACT_AST_VISITOR(NodeType) virtual auto visit(const NodeType&) -> void = 0;"},
{"lineNum":"   57","line":"#define ABSTRACT_AST_VISITOR_DECLARATION() FOREACH_AST_NODE(GENERATE_ABSTRACT_AST_VISITOR)"},
{"lineNum":"   58","line":""},
{"lineNum":"   59","line":"#define GENERATE_OVERRIDE_AST_VISITOR(NodeType) auto visit(const NodeType&) -> void override;"},
{"lineNum":"   60","line":"#define AST_VISITOR_OVERRIDES() FOREACH_AST_NODE(GENERATE_OVERRIDE_AST_VISITOR)"},
{"lineNum":"   61","line":""},
{"lineNum":"   62","line":"FORWARD_DECLARE_AST_NODES()"},
{"lineNum":"   63","line":""},
{"lineNum":"   64","line":"class Visitor {","class":"lineCov","hits":"1","order":"1078",},
{"lineNum":"   65","line":"  public:"},
{"lineNum":"   66","line":"    virtual ~Visitor() = default;","class":"lineCov","hits":"1","order":"1079",},
{"lineNum":"   67","line":"    ABSTRACT_AST_VISITOR_DECLARATION()"},
{"lineNum":"   68","line":"};"},
{"lineNum":"   69","line":""},
{"lineNum":"   70","line":"} // namespace conch::ast"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-03-13 16:31:19", "instrumented" : 2, "covered" : 2,};
var merged_data = [];
