#pragma once

#include "lexer/token.h"

#include "util/mem.h"

// clang-format off
#define OP(str, tok) {{str, sizeof(str) - 1}, tok}
// clang-format on

static const size_t MAX_OPERATOR_LEN = 3;

typedef struct {
    Slice     slice;
    TokenType type;
} Operator;

#define OPERATOR_ASSIGN OP("=", ASSIGN)
#define OPERATOR_WALRUS OP(":=", WALRUS)
#define OPERATOR_PLUS OP("+", PLUS)
#define OPERATOR_PLUS_ASSIGN OP("+=", PLUS_ASSIGN)
#define OPERATOR_MINUS OP("-", MINUS)
#define OPERATOR_MINUS_ASSIGN OP("-=", MINUS_ASSIGN)
#define OPERATOR_STAR OP("*", STAR)
#define OPERATOR_STAR_ASSIGN OP("*=", STAR_ASSIGN)
#define OPERATOR_STAR_STAR OP("**", STAR_STAR)
#define OPERATOR_SLASH OP("/", SLASH)
#define OPERATOR_SLASH_ASSIGN OP("/=", SLASH_ASSIGN)
#define OPERATOR_PERCENT OP("%", PERCENT)
#define OPERATOR_PERCENT_ASSIGN OP("%=", PERCENT_ASSIGN)
#define OPERATOR_BANG OP("!", BANG)
#define OPERATOR_WHAT OP("?", WHAT)

#define OPERATOR_AND OP("&", AND)
#define OPERATOR_AND_ASSIGN OP("&=", AND_ASSIGN)
#define OPERATOR_OR OP("|", OR)
#define OPERATOR_OR_ASSIGN OP("|=", OR_ASSIGN)
#define OPERATOR_SHL OP("<<", SHL)
#define OPERATOR_SHL_ASSIGN OP("<<=", SHL_ASSIGN)
#define OPERATOR_SHR OP(">>", SHR)
#define OPERATOR_SHR_ASSIGN OP(">>=", SHR_ASSIGN)
#define OPERATOR_NOT OP("~", NOT)
#define OPERATOR_NOT_ASSIGN OP("~=", NOT_ASSIGN)
#define OPERATOR_XOR OP("^", XOR)
#define OPERATOR_XOR_ASSIGN OP("^=", XOR_ASSIGN)

#define OPERATOR_LT OP("<", LT)
#define OPERATOR_LTEQ OP("<=", LTEQ)
#define OPERATOR_GT OP(">", GT)
#define OPERATOR_GTEQ OP(">=", GTEQ)
#define OPERATOR_EQ OP("==", EQ)
#define OPERATOR_NEQ OP("!=", NEQ)

#define OPERATOR_COLON_COLON OP("::", COLON_COLON)
#define OPERATOR_DOT OP(".", DOT)
#define OPERATOR_DOT_DOT OP("..", DOT_DOT)
#define OPERATOR_DOT_DOT_EQ OP("..=", DOT_DOT_EQ)
#define OPERATOR_FAT_ARROW OP("=>", FAT_ARROW)
#define OPERATOR_COMMENT OP("//", COMMENT)
#define OPERATOR_MULTILINE_STRING OP("\\\\", MULTILINE_STRING)
#define OPERATOR_REF OP("ref", REF)

static const Operator ALL_OPERATORS[] = {
    OPERATOR_ASSIGN,
    OPERATOR_WALRUS,
    OPERATOR_PLUS,
    OPERATOR_PLUS_ASSIGN,
    OPERATOR_MINUS,
    OPERATOR_MINUS_ASSIGN,
    OPERATOR_STAR,
    OPERATOR_STAR_ASSIGN,
    OPERATOR_STAR_STAR,
    OPERATOR_SLASH,
    OPERATOR_SLASH_ASSIGN,
    OPERATOR_PERCENT,
    OPERATOR_PERCENT_ASSIGN,
    OPERATOR_BANG,
    OPERATOR_WHAT,

    OPERATOR_AND,
    OPERATOR_AND_ASSIGN,
    OPERATOR_OR,
    OPERATOR_OR_ASSIGN,
    OPERATOR_SHL,
    OPERATOR_SHL_ASSIGN,
    OPERATOR_SHR,
    OPERATOR_SHR_ASSIGN,
    OPERATOR_NOT,
    OPERATOR_NOT_ASSIGN,
    OPERATOR_XOR,
    OPERATOR_XOR_ASSIGN,

    OPERATOR_LT,
    OPERATOR_LTEQ,
    OPERATOR_GT,
    OPERATOR_GTEQ,
    OPERATOR_EQ,
    OPERATOR_NEQ,

    OPERATOR_COLON_COLON,
    OPERATOR_DOT,
    OPERATOR_DOT_DOT,
    OPERATOR_DOT_DOT_EQ,
    OPERATOR_FAT_ARROW,
    OPERATOR_COMMENT,
    OPERATOR_MULTILINE_STRING,
    OPERATOR_REF,
};
